# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Slack_Clone_Pro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Slack_Clone_Pro

  target 'Slack_Clone_ProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Slack_Clone_ProUITests' do
    # Pods for testing
  end

pod "RxFlow"
pod 'Firebase/Messaging'
pod 'Alamofire'
pod "SnapKit" 
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Reusable'
end
